stages:
  - build

build:
  tags:
    - docker
  stage: build
  image:
    name: docker:dind
    entrypoint: [""]
  script:
    - docker login --username ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}/${CI_PROJECT}
    - cd ${CI_PROJECT_DIR}
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT}/${CI_PROJECT}:${CI_COMMIT_TAG} .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_NAME}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}
